### ISSUE TITLE
Spotlight search animation significantly slower.

### ISSUE THREAD

**Issue by aboodixd** [Muirey03/Zenith#30]
I disabled this tweak and spotlight was fine, disabled all other tweaks and kept this installed and spotlight felt laggy.

**Comment by Muirey03** [comment]
It's not lag. Due to the previous search gesture obstructing the swipe down on icons, it has been replaced with the option to swipe down on the wallpaper or tap the status bar to present it (configurable from settings). If you choose the swiping down on the wallpaper, the way iOS gestures work is that spotlight won't appear until you have completed the swipe-down, and will then animate in with the default duration. I would recommend choosing the tap on status bar option instead then.

**Comment by aboodixd** [comment]
Ah ok. Would it be possible to make an option so that only swiping up on the app opens up zenith, so that the swipe down would still work normally? Or would that not make a difference?
