### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by kraxarn** [Muirey03/Zenith#55]
Because the bugs I've noticed with this tweak aren't getting fixed, I would like to request a refund. I've already reported it to PayPal, but I just wanted to get a response from you before I escalate it to PayPal.

**Comment by Muirey03** [comment]
You cannot request a refund through PayPal I believe as the payment does not got directly to me, it goes through the chariz platform, so you have to request a refund there. The reason your "bugs" are not being fixed, is because they are not actually bugs. The first is an issue with bolders and not my fault/something I would be able to fix, and the second is an enhancement suggestion that is entirely impossible without entirely rewriting the logic for the expansion of stacks, which is not something I am willing to do as it would be an immense amount of work for one minor and unnecessary enhancement, and because it in itself will cause its own issues and problems for other users and because there is nothing wrong with it as it is, all other users are happy with it in its current state. Therefore I hardly see this as grounds for a refund as the tweak works perfectly standalone, I have no obligation to fulfil requests and the only "bug" you reported is not my fault.

**Comment by kraxarn** [comment]
I'm just comparing this to Apex 2, which had more features, less bugs and was free.

**Comment by Muirey03** [comment]
Honestly, what?! Apex 2 was the same price, had **MORE** bugs (this is bug-free by itself, Apex 2 had a bug where you would need to respring after adding an icon to a stack!) and **LESS** features. All the features that were in Apex are in here too, plus some more! Please don't try to make up evidence so you can get a refund, that's just petty...

**Comment by kraxarn** [comment]
Apex 2 is __free__ and I never had any resprings or major issues with it.

**Comment by Muirey03** [comment]
Apex 2 has only been made free since the creator dropped support for it, it used to be $2 like Zenith, and Zenith will be free too when I drop support for it. You will never have any resprings or major issues with Zenith either, unless you use conflicting tweaks, and all conflicting tweaks will be alerted to you on install.
